# Generated by Django 2.0.1 on 2018-01-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0002_plantphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantphoto',
            old_name='photo',
            new_name='photo_name',
        ),
    ]
